apiVersion: v1
kind: Service
metadata:
  labels:
    name: haute-code-service
  name: haute-code-service
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"haute-backend-config"}}'
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    name: haute-code
  sessionAffinity: None
  type: LoadBalancer
